[package]
name = "timecop"
version = "0.1.0"
authors = ["Max <code@workwithmax.com>"]
edition = "2018"

[dependencies]
num = "0.4.0"
git2 = "0.13.19"
termion = "1.5"
sqlite = "0.26.0"
home = "0.5.3"
chrono = "0.4.19"
dialoguer = "0.8.0"
clap = "2.33.3"
textwrap = "0.13.4"
csv = "1.1.6"
