name: Clippy

on: [push]

jobs:
  release:
    name: Run linter
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
